## Main configuration values
main:
    ## restart modes availiable 'interval', and 'timestamp'
    restart_mode: 'interval'
    ## restart mode specific settings
    modes:
        ## Interval in Hours (DECIMALS ALLOWED)
        interval: 3.0
        ## Set the timestamp in 24 hour time format HH:MM
        timestamp: '6:00'
    ## Server wide prefix for all chat broadcasts
    prefix: '&f[&7AutoRestart&f] &e'
    ## Client restart message when kicked
    restart_message: '&cServer Restarting! We will be back up any minute!'

## Reminders will popup in the specified times to let players know when is the next restart
reminder:
    ## Enables or Disables restart reminder
    enabled:
        minutes: true
        seconds: true
    ## minutes before restart
    minutes:
        - 15
        - 10
        - 5
        - 1
    ## AutoRestart will countdown the seconds to restart starting at the entered value
    seconds: 5

## Global Broadcast and Player Messages adds flexibility on what you want your players to see!
## You have the option of having the player who executed the event to see a message while other dont, or
## have the player who executed the event see a global message but not a private message, or both!
## you can have the server see a global message while the player who executed the command will see
## his own message.

## The reason why you can enable or disable broadcasts and popups, is to give you the flexibility to
## choose whether you want your players to see a broadcast or a popup of the event. Or both! If you have
## both popups and broadcasts disabled, broadcasts are automaticlly enabled. If broadcasts player messages,
## and popups are all disabled, then it will aswell be automaticlly enabled in broadcasts.
    
## These are global broadcasts the everyone sees. If the same task is enabled in "player_messages"
##  the player who initiated the event will not see the broadcast, but will see his own broadcast.
##  Global broadcasts include the prefix in "main.prefix" config.
global_broadcast:
    ## Enable or Disable the broadcast
    enabled:
        ## Show the broadcast on the minute reminders!
        minutes: true
        ## Show the broadcast on the last seconds of a server restart! [Duplicated in Player_Messages]
        seconds: true
        ## Show the broadcast when typed /autore start or /autore pause
        status:
            start: true
            pause: true
        ## Show the broadcast when the server time has been changed! [Duplicated in Player_Messages]
        change: true
        ## Show the Maxplayers broadcast
        max_players:
            ## The message broadcasted when too many players are online on restart!
            alert: true
            ## This message appears when the amount of players requirement is met!
            pre_shutdown: true
    ## The configuration for broadcast messages
    ## Messages have multi line support!
    messages:
        ## %m - minutes
        minutes:
        - 'Server Will Restart In %m Minutes!'
        ## %s - seconds
        seconds:
        - 'Server is restarting in %s Seconds!'
        ## There are no tags for this section.
        status:
            start:
            - '&cAutoRestart timer has started!'
            pause:
            - '&cAutoRestart timer has been paused'
        ## %h - hours, %m - minutes, %s - seconds
        change:
        - '&cServer now is restarting in &f%h&cH &f%m&cM &f%s&cS!'
        ## Maxplayers broadcast settings
        max_players:
            ## The message broadcasted when too many players are online on restart!
            ## %a - amount
            alert:
            - '&bToo many players online for restart. Max &f%a&b amount of players allowed for a restart. Waiting for people to leave!'
            ## This message appears when the amount of players requirement is met!
            ## %d - delay
            pre_shutdown:
            - '&aServer now restarting in &f%d&a seconds!'

## These are private messages sent to the player when the event is triggered. If the same task is enabled in
##  "global_broadcast", this player will not see the global message, but his own.
##  Player messages do not include the prefix in "main.prefix" config.
player_messages:
    ## Enable or Disable the chat message
    enabled:
        ## Show the message when type /autore time
        time: true
        ## Show the message when typed /autore start or /autore pause [Duplicated in Global_Messages]
        status:
            start: true
            pause: true
        ## Show the broadcast when the server time has been changed!
        change: true
    messages:
        ## %h - hours, %m - minutes, %s - seconds
        time:
        - '&cServer restarting in &f%h&cH &f%m&cM &f%s&cS!'
        ## There are no tags for this section.
        status:
            start:
            - '&cAutoRestart timer has started!'
            pause:
            - '&cAutoRestart timer has been paused'
        ## %h - hours, %m - minutes, %s - seconds
        change:
        - '&cServer now is restarting in &f%h&cH &f%m&cM &f%s&cS!'

## This will stop your server from shutting down if you have more than X amount of players configured in "amount".
max_players:
    ## Enable or Disable this feature
    enabled: false
    ## The max amount of players allow for a restart. If you set this to 10, and your server has 11 people online
    ## your server will not shutdown until there is LESS THAN 10 players.
    amount: 10
    ## The delay for the server to restart once player count as been met. In seconds!
    delay: 10

## DO NOT EDIT VERSION NUMBER!
version: 0