name: AutoRestart
version: 3.2.0
main: me.dennis.autorestart.core.AutoRestart
author: ServersMC, DennisLysenko
commands:
    autore:
        description: 'Main AutoRestart command.'
        usage: '/autore help'